import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Shack NextLernen",
    template: "%s | Just Try", 
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header>
          <p style={{ padding: "1rem", backgroundColor: "red" }}>Header</p>
        </header>
        {children}
        <footer>
          <p style={{ padding: "1rem", backgroundColor: "yellow" }}>Footer</p>
        </footer>
      </body>
    </html>
  );
}
